/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GameShopInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "archeryItems"
      | "buyItem"
      | "getItemInfo"
      | "roleManager"
      | "shopCatalog"
      | "treasury"
      | "updateItem"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CatalogUpdated" | "ItemPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "archeryItems",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyItem",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getItemInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "roleManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "shopCatalog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateItem",
    values: [BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "archeryItems",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getItemInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shopCatalog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateItem", data: BytesLike): Result;
}

export namespace CatalogUpdatedEvent {
  export type InputTuple = [
    skuId: BigNumberish,
    price: BigNumberish,
    maxSupply: BigNumberish,
    active: boolean
  ];
  export type OutputTuple = [
    skuId: bigint,
    price: bigint,
    maxSupply: bigint,
    active: boolean
  ];
  export interface OutputObject {
    skuId: bigint;
    price: bigint;
    maxSupply: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    skuId: BigNumberish,
    qty: BigNumberish,
    price: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    skuId: bigint,
    qty: bigint,
    price: bigint
  ];
  export interface OutputObject {
    buyer: string;
    skuId: bigint;
    qty: bigint;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameShop extends BaseContract {
  connect(runner?: ContractRunner | null): GameShop;
  waitForDeployment(): Promise<this>;

  interface: GameShopInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  archeryItems: TypedContractMethod<[], [string], "view">;

  buyItem: TypedContractMethod<
    [skuId: BigNumberish, quantity: BigNumberish],
    [void],
    "payable"
  >;

  getItemInfo: TypedContractMethod<
    [skuId: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        supply: bigint;
        maxSupply: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  roleManager: TypedContractMethod<[], [string], "view">;

  shopCatalog: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        maxSupply: bigint;
        currentSupply: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  updateItem: TypedContractMethod<
    [
      skuId: BigNumberish,
      price: BigNumberish,
      maxSupply: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "archeryItems"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "buyItem"
  ): TypedContractMethod<
    [skuId: BigNumberish, quantity: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getItemInfo"
  ): TypedContractMethod<
    [skuId: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        supply: bigint;
        maxSupply: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "roleManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "shopCatalog"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, boolean] & {
        price: bigint;
        maxSupply: bigint;
        currentSupply: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateItem"
  ): TypedContractMethod<
    [
      skuId: BigNumberish,
      price: BigNumberish,
      maxSupply: BigNumberish,
      active: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CatalogUpdated"
  ): TypedContractEvent<
    CatalogUpdatedEvent.InputTuple,
    CatalogUpdatedEvent.OutputTuple,
    CatalogUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ItemPurchased"
  ): TypedContractEvent<
    ItemPurchasedEvent.InputTuple,
    ItemPurchasedEvent.OutputTuple,
    ItemPurchasedEvent.OutputObject
  >;

  filters: {
    "CatalogUpdated(uint256,uint256,uint256,bool)": TypedContractEvent<
      CatalogUpdatedEvent.InputTuple,
      CatalogUpdatedEvent.OutputTuple,
      CatalogUpdatedEvent.OutputObject
    >;
    CatalogUpdated: TypedContractEvent<
      CatalogUpdatedEvent.InputTuple,
      CatalogUpdatedEvent.OutputTuple,
      CatalogUpdatedEvent.OutputObject
    >;

    "ItemPurchased(address,uint256,uint256,uint256)": TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;
    ItemPurchased: TypedContractEvent<
      ItemPurchasedEvent.InputTuple,
      ItemPurchasedEvent.OutputTuple,
      ItemPurchasedEvent.OutputObject
    >;
  };
}
